name: Build all-in-one

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  # Run on PRs except for documentation
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
  IMAGE_NAME: hercules-aio
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}

jobs:

  build-aio:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        HERCULES_SERVER_MODE: ['renewal', 'classic']
        HERCULES_PACKET_VERSION: ['latest', '20180418']

    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - uses: haya14busa/action-cond@v1
        id: image_tags
        name: Define tags for image
        with:
          # Mark classic image with packet version 20180418 as the default on "hercules" repo
          cond: ${{ matrix.HERCULES_SERVER_MODE == 'classic' && matrix.HERCULES_PACKET_VERSION == '20180418' }}
          if_true: |
            florianpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}:latest
            florianpiesche/hercules:${{ matrix.HERCULES_SERVER_MODE }}-packetver-${{ matrix.HERCULES_PACKET_VERSION }}
            florianpiesche/hercules:latest
            ghcr.io/fpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}:latest
            ghcr.io/fpiesche/hercules:${{ matrix.HERCULES_SERVER_MODE }}-packetver-${{ matrix.HERCULES_PACKET_VERSION }}
            ghcr.io/fpiesche/hercules:latest
          if_false: |
            florianpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}:latest
            florianpiesche/hercules:${{ matrix.HERCULES_SERVER_MODE }}-packetver-${{ matrix.HERCULES_PACKET_VERSION }}
            ghcr.io/fpiesche/hercules-${{ matrix.HERCULES_SERVER_MODE }}-${{ matrix.HERCULES_PACKET_VERSION }}:latest
            ghcr.io/fpiesche/hercules:${{ matrix.HERCULES_SERVER_MODE }}-packetver-${{ matrix.HERCULES_PACKET_VERSION }}

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build ${{ env.IMAGE_NAME }} Docker image
        uses: docker/build-push-action@v2
        with:
          context: hercules-build
          file: hercules-build/Dockerfile.all-in-one
          tags: ${{ steps.image_tags.outputs.value }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
