name: Build Hercules build environment

on:
  # Allow manual runs.
  workflow_dispatch:
  # Run on merges and PRs to builder Dockerfile.
  push:
    branches:
      - main
    paths:
      - 'hercules-build/docker-stages/create-builder.dockerfile'
  pull_request:
    paths:
      - 'hercules-build/docker-stages/create-builder.dockerfile'

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
  IMAGE_NAME: hercules-builder
  # PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}
  PUSH_IMAGE: 'true'

jobs:

  build-builder:
    name: Build Hercules builder image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build ${{ env.IMAGE_NAME }} Docker image
        uses: docker/build-push-action@v2
        with:
          context: hercules-build
          file: hercules-build/docker-stages/create-builder.dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/hercules:latest
            ghcr.io/${{ github.repository_owner }}/hercules:latest
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
